### ISSUE TITLE
broken link  https://csinva.github.io/blog/interpretability

### ISSUE THREAD

**Issue by Sandy4321** [csinva/csinva.github.io#1]
broken link  https://csinva.github.io/blog/interpretability

**Comment by csinva** [comment]
Sorry about this. Fixed now, thanks for pointing it out!

P.S. the [website](https://csinva.github.io/#notes_main) has more links than the readme file if you are interested.

**Comment by Sandy4321** [comment]
sure will check
by the way I try to run
https://github.com/csinva/interpretability-implementations-demos/tree/master/imodels/rulefit

how different this performance from sbrl ?
