### ISSUE TITLE
need suggestion of your resume builder

### ISSUE THREAD

**Issue by Tharun-tharun** [csinva/csinva.github.io#4]
just saw resume of yours by the way that was a simple and awesome resume, do you have any suggestion on resume builder just like yours template.

**Comment by csinva** [comment]
I think the most similar is the deedy template available [here](https://www.overleaf.com/latex/templates/deedy-cv/bjryvfsjdyxz)

**Comment by Tharun-tharun** [comment]
> I think the most similar is the deedy template available [here](https://www.overleaf.com/latex/templates/deedy-cv/bjryvfsjdyxz)

Thanks a lot for providing it, by the way, I admire your resume and your work do you have do have an email id, if you do can you share yours, so that it will be easy for me to contact you for further doubts and clarification in future. Thank you
